// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	externalRef0 "github.com/Jack-R-lantern/site/internal/api/models"
	"github.com/gin-gonic/gin"
)

// DetachProgramJSONRequestBody defines body for DetachProgram for application/json ContentType.
type DetachProgramJSONRequestBody = externalRef0.AttachRequest

// AttachProgramJSONRequestBody defines body for AttachProgram for application/json ContentType.
type AttachProgramJSONRequestBody = externalRef0.AttachRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Detach BPF program in an idempotent way
	// (DELETE /api/v1/program/attachment)
	DetachProgram(c *gin.Context)
	// Attach BPF program in an idempotent way
	// (PUT /api/v1/program/attachment)
	AttachProgram(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DetachProgram operation middleware
func (siw *ServerInterfaceWrapper) DetachProgram(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DetachProgram(c)
}

// AttachProgram operation middleware
func (siw *ServerInterfaceWrapper) AttachProgram(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AttachProgram(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/api/v1/program/attachment", wrapper.DetachProgram)
	router.PUT(options.BaseURL+"/api/v1/program/attachment", wrapper.AttachProgram)
}
