// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

// Defines values for AttachRequestProgType.
const (
	AttachRequestProgTypeNode AttachRequestProgType = "node"
	AttachRequestProgTypePod  AttachRequestProgType = "pod"
)

// Defines values for DetachRequestProgType.
const (
	DetachRequestProgTypeNode DetachRequestProgType = "node"
	DetachRequestProgTypePod  DetachRequestProgType = "pod"
)

// AttachRequest defines model for AttachRequest.
type AttachRequest struct {
	// Egress egress direction attach whether
	Egress bool `json:"egress"`

	// Ingress ingress direction attach whether
	Ingress bool `json:"ingress"`

	// ProgType bpf attach point
	ProgType AttachRequestProgType `json:"progType"`
}

// AttachRequestProgType bpf attach point
type AttachRequestProgType string

// DetachRequest defines model for DetachRequest.
type DetachRequest struct {
	// Egress egress direction detach whether
	Egress bool `json:"egress"`

	// Ingress ingress direction detach whether
	Ingress bool `json:"ingress"`

	// ProgType bpf detach point
	ProgType DetachRequestProgType `json:"progType"`
}

// DetachRequestProgType bpf detach point
type DetachRequestProgType string
