// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

// Defines values for AttachRequestProgType.
const (
	Node AttachRequestProgType = "node"
	Pod  AttachRequestProgType = "pod"
)

// AttachRequest defines model for AttachRequest.
type AttachRequest struct {
	// Egress egress direction attach whether
	Egress bool `json:"egress"`

	// Ingress ingress direction attach whether
	Ingress bool `json:"ingress"`

	// ProgType bpf attach point
	ProgType AttachRequestProgType `json:"progType"`
}

// AttachRequestProgType bpf attach point
type AttachRequestProgType string
